import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ClientLayout from "../components/ClientLayout";
import theme from "../theme";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${roboto.variable}`}>
        <AppRouterCacheProvider>
          <ClientLayout>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </ClientLayout>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
